# Generated by Django 5.0.6 on 2024-06-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_board_user_id_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='user_id',
            new_name='user',
        ),
    ]
