# Generated by Django 5.0.6 on 2024-06-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_role_alter_board_name_alter_column_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='can_manage_all_tasks',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_board',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_columns',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_own_tasks',
        ),
    ]
