# Generated by Django 5.0.6 on 2024-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_role_can_manage_all_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_change_executor',
            field=models.BooleanField(default=False, verbose_name='Can change executor of the task'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_tasks',
            field=models.BooleanField(default=False, verbose_name='Can create tasks. Can manage only own tasks(edit and delete)'),
        ),
    ]
