# Generated by Django 5.0.6 on 2024-06-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_boardmemberrelation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_all_tasks',
            field=models.BooleanField(default=False, verbose_name='Can edit and delete all tasks(not only own)'),
        ),
    ]
